//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanshenDiplomWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCard
    {
        public int Id { get; set; }
        public string Num { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public Nullable<int> CVC { get; set; }
    }
}
