//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanshenDiplomWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VanshenDatabaseEntities1 : DbContext
    {
        public VanshenDatabaseEntities1()
            : base("name=VanshenDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<BankCard> BankCard { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Filter> Filter { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductFilter> ProductFilter { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
